site_name: Insure People
theme: 
  name: material
  logo: ""

  features:
    #- navigation.tabs # uncomment this to make navigation on top
    - navigation.sections
    - toc.integrate
    - navigation.footer

nav:
- 'index.md'
- 'key.md'
- 'concreteinput.md'
- 'comparisonexample.md'
- 'slideyouself.md'
- 'toughchoices.md'
- 'noki.md'
- 'feedback.md'
- 'bangladesh.md'

